### ISSUE TITLE
Page assign still wrong.

### ISSUE THREAD

**Issue by KienTrong** [FameThemes/onepress-demo-importer#1]
Already sync
1. Home Setting can't assign.
2. Primary doesn't display.
3. Service and About assign wrong page.

Need solve.

**Comment by shrimp2t** [comment]
1. Home Setting can't assign - Fixed
2. Primary doesn't display. - Tested with empty data and already have data before import - Work.
3. Service and About assign wrong page. - Checked with demo page - It's look like demo page
